# 自定义文件保存路径
gorit:
  file:
    root:
      path: D:\ideaProject\Landlor\src\main\webapp\upload\
server:
  port: 8879
spring:
  dubbo:
    application:
      id: dubbo-customer
      name: dubbo-customer
      logger: slf4j
  datasource:
    druid:
        max-active: 10
        min-idle: 5
        max-wait: 5000
        initial-size: 5
        validation-query: select 1
        stat-view-servlet:
          enabled: true
          url-pattern: "/druid/*"
        web-stat-filter:
          enabled: true
          url-pattern: "/druid/**"
          exclusions: '*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*'
          principal-session-name: ''
          session-stat-enable: true
          session-stat-max-count: 1000
        filters: "stat,wall,logback"
    thymeleaf:
      cache: false
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss     # 配置全局时间格式  jsonformate  timefromat
      time-zone: GMT+8
  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2KB # 文件写入磁盘的阈值
      max-file-size: 100MB
      max-request-size: 215MB # 最大请求值大小
dubbo:
  appname: landlor-controller
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol: dubbo
  application:
    id: dubbo-customer
    name: dubbo-customer
    logger: slf4j
redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址（默认为loaclhost）
    host: loaclhost
    # redis端口（默认为6379）
    post: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位毫秒）
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

shiro:
  hash-iterations: 2
  hash-algorithm-name: md5
  login-url: /index.html
  unauthorized-url: /unauthorized.html
  anon-urls:
    - /api/login/doLogin*
    - /druid/**
    - /swagger-ui.html
    - /webjars/**
    - /swagger-resources/**
    - /v2/**
    - /api/login/captcha
    - /api/login/checkLogin
  logout-url: /api/login/logout*
  authc-urls:
    - /**