server:
  port: 8878
dubbo:
  appname: landlor-servise
  registry:
   address: zookeeper://127.0.0.1:2181
  protocol: dubbo
  port: 20880
  application:
    id: dubbo-provice
    name: dubbo-provice
    logger: slf4j
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/landlord?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
logging:
  pattern:
    console: '%d -%msg%n'
  path: D:/data/log/service.log
  level:
    com.lym.mapper: debug


mybatis:
  mapper-locations: classpath:mapper/*.xml